### ISSUE TITLE
`(gnome-network-displays:2): Gnd-ERROR **: *CcHttpServer: Failed to create gst elements`

### ISSUE THREAD

**Issue by Raakh** [flathub/org.gnome.NetworkDisplays#159]
I am tried to install following the instructions here https://flatpak.org/setup/Ubuntu

linux@dell ~> flatpak run org.gnome.NetworkDisplays

(gnome-network-displays:2): Gnd-ERROR **: 19:03:03.137: CcHttpServer: Failed to create gst elements

Trying to connect my Smart-TV (Olive 4k Android TV that uses Fascast software) but fails with the aforementioned error My

More info on my environment here: https://pastebin.ubuntu.com/p/SNj7tBwRQQ/

Best Regards

**Comment by LorbusChris** [comment]
This is tracked upstream at https://gitlab.gnome.org/GNOME/gnome-network-displays/-/issues/298
It'll be fixed with the next release, that I'll hopefully come around to cutting soon.

**Comment by LorbusChris** [comment]
Should be fixed now.
