### ISSUE TITLE
Sync manifest upstream

### ISSUE THREAD

**Issue by Naheem** [flathub/org.gnome.NetworkDisplays#62]
The manifest here is much more updated compared to the flatpak manifest upstream.

I have tried copying it but it needs a greater understanding that I currently have - a straight copy does not work.

If the changes can be upstreamed that would be much appreciated.

https://gitlab.gnome.org/GNOME/gnome-network-displays/-/merge_requests/166

**Comment by Lctrs** [comment]
You'll need to copy paste the `files/` and `patches/` directories at the root of the repository as well.

For the first module of the list that we refer from `shared-modules/`, you can replace it by its definition in the repo. It should give something like this : 

```json
...
"modules": [
        {
  "name": "intltool",
  "cleanup": [ "*" ],
  "sources": [
    {
      "type": "archive",
      "url": "https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz",
      "sha256": "67c74d94196b153b774ab9f89b2fa6c6ba79352407037c8c14d5aeb334e959cd"
    },
    {
      "type": "patch",
      "path": "intltool-perl5.26-regex-fixes.patch"
    }
  ]
},
        {
            "name": "gst-rtsp-server",
            "buildsystem": "meson",
            "builddir": true,
            "config-opts": [
                "-Dexamples=disabled",
                "-Dtests=disabled",
                "-Dintrospection=disabled"
            ],
            "cleanup": [
                "/include",
                "/lib/pkgconfig"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://gstreamer.freedesktop.org/src/gst-rtsp-server/gst-rtsp-server-1.18.6.tar.xz",
                    "sha256": "826f32afbcf94b823541efcac4a0dacdb62f6145ef58f363095749f440262be9",
                    "x-checker-data": {
                        "type": "json",
                        "url": "https://gitlab.freedesktop.org/api/v4/projects/1362/repository/tags?search=^1.18.",
                        "version-query": ".[0].name",
                        "url-query": "\"https://gstreamer.freedesktop.org/src/gst-rtsp-server/gst-rtsp-server-\" + $version + \".tar.xz\""
                    }
                }
            ]
        },
        ....
]
```

You'll need to take the patch in shared-modules as well.

**Comment by Naheem** [comment]
Thanks for the help. I had tried that yesterday but it didn't work - I had probably made some typos or something (it failed with not being able to locate gstreamer-1), but today it has worked.

Upstream merge request: https://gitlab.gnome.org/GNOME/gnome-network-displays/-/merge_requests/169

**Comment by Lctrs** [comment]
@Naheem In your MR, you can delete the `x-checker-data` key in all modules. They have no purpose in your case.

**Comment by Naheem** [comment]
Thanks, I have removed that.

I also also removed the build config "-Dfirewalld_zone=false" because that seemed to stop connections (though I have a bigger issue here - I cant seem to get a sink device to work on flatpak, or from gnome-builder.). With this gone (or if it should be brought back, please let me know).

With that gone, is there any purpose of keeping firewalld included? It seems unused now. and building works just as well without it. i tried checking history on here to see why it was added, but it seems to exist from the first commit.

**Comment by Lctrs** [comment]
It's related to this issue : https://gitlab.gnome.org/GNOME/gnome-network-displays/-/issues/134

We don't want to let gnd install its own firewall rule (point 1 on the issue) because it doesn't have access to that path. Instead, we want it to create its own firewalld zone by using firewalld API (point 2).

**Comment by Naheem** [comment]
This has been merged.
