### ISSUE TITLE
Not working on Fedora 36 and Silverblue 36

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/org.gnome.NetworkDisplays#73]
Installing RPM version is working as expected but flathub version just never start to scan the network.

Any idea ?

**Comment by Lctrs** [comment]
Without any log, no idea.

**Comment by bellegarde-c** [comment]
Sadly, there are no logs, it just freeze :(

**Comment by bellegarde-c** [comment]
@Lctrs Is there any particular reason about using current unstable version ?

**Comment by benzea** [comment]
Can you test the fix in https://gitlab.gnome.org/GNOME/gnome-network-displays/-/merge_requests/175?
