### ISSUE TITLE
Starting to stream failed

### ISSUE THREAD

**Issue by robertoswald** [flathub/org.gnome.NetworkDisplays#89]
## System Information

- Manufacturer: Dell Inc.
- Product Name: XPS 13 7390

## OS

- Ubuntu 22.04
- Xorg

## Network Display 

- miracast dongle

## Gnome Network Displays

- GNOME Network Displa… org.gnome.NetworkDisplays           0.90.4               stable     system

## Failed to stream

```bash
flatpak run org.gnome.NetworkDisplays
Gtk-Message: 18:39:30.374: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:39:30.375: Failed to load module "canberra-gtk-module"

** (gnome-network-displays:2): WARNING **: 18:39:54.200: WfdClient: No resolution found, falling back to standard FullHD resolution.
```

Crashes after "establishing connection" when "starting to stream".

**broken after:**
`sudo flatpak update --commit=da4cc6da0424278d0981b55ec0b70528a73dfe511880f2e23b0a176ff3c58987 org.gnome.NetworkDisplays`

**works until:**
`sudo flatpak update --commit=f45d9be01f48536a4f9fca907b60cdefdc709572faf63bd845f412e86b86bf3e org.gnome.NetworkDisplays`

**Comment by Lctrs** [comment]
Do the latest updates fix your situation ?

**Comment by robertoswald** [comment]
The problem exists in:
GNOME Network Displays	org.gnome.NetworkDisplays	0.90.4	stable	system

**Comment by almereyda** [comment]
It appears this is mostly covered by

- https://gitlab.gnome.org/GNOME/gnome-network-displays/-/issues/279

and not specifically a FlatPak packaging issue.

Suggesting to close here in favour of tracking upstream.
